### ISSUE TITLE
Discussion pages not parsed (OSError: [Errno 22] Invalid argument:...)

### ISSUE THREAD

**Issue by BagelHero** [bodekerscientific/wikidot_tools#1]
Hi! Apologies if you don't check issues on this repo or have time to reply, I'll keep trying to solve on my own but thought it was worth a shot.

Things proceed as normal until I get to certain kinds of names or subpages; particularly names with unexpected additional colons (:). This was somewhat expected and something I was prepared to manually go in and fix on a per-page level (we can have unusual user-generated names with symbols on this wiki), but unfortunately it seems to also catch _typical_ subpages. For example, one called `/talk:utau:gekiyaku`, which is the discussion page for the main wiki page `/utau:gekiyaku`. This appears to be normal for how these pages are handled on wikidot unless I'm mistaken.

Error:
```
   Downloading: 'talk_utau:gekiyaku'
Traceback (most recent call last):
  File "E:\Wiki Resources\wikidot_tools-main\wikidot_tools-main\FancyDownloader.py", line 202, in <module>
    fire.Fire(run_multi)
  File "C:\Users\Bagel\AppData\Local\Programs\Python\Python312\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bagel\AppData\Local\Programs\Python\Python312\Lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bagel\AppData\Local\Programs\Python\Python312\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Wiki Resources\wikidot_tools-main\wikidot_tools-main\FancyDownloader.py", line 140, in run_multi
    run(site_n, url, output_folder)
  File "E:\Wiki Resources\wikidot_tools-main\wikidot_tools-main\FancyDownloader.py", line 182, in run
    DownloadPage(pageName, site_name, url)
  File "E:\Wiki Resources\wikidot_tools-main\wikidot_tools-main\FancyDownloader.py", line 64, in DownloadPage
    with open(localName + ".txt", "wb") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'talk_utau:gekiyaku.txt'
```
I'm a novice, but I'll keep trying things. Feel free to let me know if it's not technically a bug or is an issue on my end, too; I understand this just may not be what your organisation needed it for :) 

Ideally if this issue can't be fixed directly it would be great if the script skipped pages that encounter this error & continued through the remaining pages on the wiki, if anyone particularly enterprising sees this.

That said, for the pages that make it through, the output is extremely promising. I have hope of being able to get it backed up in some kind of form that remains editable, so I'd also like to say thank you for providing an easy way to use these tools.

**Comment by mattgwwalker** [comment]
Hi,

It looks like you're using this under Windows.  It's been a long time since
I have used a Windows system, and we only tested this code in Linux.  I
understand that a colon isn't an acceptable character in a Windows filename
(while it would be ok under Linux).  So that might be the root of our issue.

In the copy of your Wiki, can you find a file named something like
'talk_utau:gekiyaku.txt'?  If there's an obvious mapping from the colon to
something else, that might help us work out what to do.

Cheers,

Matthew

**Comment by mattgwwalker** [comment]
I had a closer look at that stack trace and it's failing to actually download.  I had assumed that it was failing to process the file.  So this is indeed because (exactly as you described) there are colons in the page name.

You can see in [line 157 of FancyDownloader.py](https://github.com/bodekerscientific/wikidot_tools/blob/94530857addfa8908d48d27d184cdf1b8636ea64/FancyDownloader.py#L157C1-L157C1) that we handle the first colon between the username and the page name.  It looks like we've assumed there are no more colons to worry about.

As a quick hack to see if this helps, you could try adding after line 54:

    localName = localName.replace(":", "_")

That should allow you to download a copy of the wiki.  That change might give you new problems however when it comes to processing the files.  But step one, lets see if we can get the files downloaded.

Another option, if this is available to you, would be to run the code in a Linux system.
